### ISSUE TITLE
Error in running sample_autoencoder.py file 

### ISSUE THREAD

**Issue by simonfqy** [HIPS/molecule-autoencoder#4]
I was following the instructions on the homepage of this github repository, trying to run the sample_autoencoder.py file exactly according to the example. However, this is what showed up:

>python sample_autoencoder.py \
>         ../data/best_vae_model.json \
>         ../data/best_vae_annealed_weights.h5 \
>         ../data/250k_rndm_zinc_drugs_clean.smi \
>         ../data/zinc_char_list.json \
>         -l5000
Using Theano backend.
Traceback (most recent call last):
  File "sample_autoencoder.py", line 97, in <module>
    model = model_from_json(json.dumps(model_dict))
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 213, in model_from_json
    return layer_from_config(config, custom_objects=custom_objects)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/layer_utils.py", line 27, in layer_from_config
    class_name = config['class_name']
KeyError: 'class_name'

Can anyone please tell me what is going on here? Thank you very much!

**Comment by wadekun** [comment]
make sure you install keras from here: https://github.com/rgbombarelli/keras

1. git clone https://github.com/rgbombarelli/keras.git
2. cd keras
3. python setup.py install
